name='prInCe!!!! rAj7!!!'
print(len(name))
print(name.upper())
print(name.lower())
print(name.rstrip("!"))
print(name.replace("!", "."))
print(name.split(" "))
print(name.capitalize())
print(name.center(50))
print(name.count('r'))
print(name.endswith('!!!')) #gives boolean
print(name.find('In'))
print(name.index('C'))
print(name.isalnum())
print(name.isalpha())
print(name.islower())
print(name.isprintable())
print(name.isupper())
print(name.istitle())
print(name.isprintable())
print(name.title())